version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - database
    container_name: arzamas-api
    env_file:
      - .env/api
      - .env/database

  database:
    image: postgres:12
    env_file:
      - .env/database
    container_name: arzamas-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: